name: "Osci-Motion Lager Pro"
slug: "osci_motion_lager"
description: "Modulare Bestandsverwaltung für Osci-Motion ->DYI Projekt, keine Verbindung zum Hersteller <-"
version: "1.1.4"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
panel_icon: "mdi:flask-outline"
panel_title: "Osci-Lager"
ingress: true
ingress_port: 8099
init: false
startup: application
